organization:
    id: eb3a5222-8b17-4391-b42d-40d3031b1ac8
    name: JackyLeiSSW567
project:
    id: 4eb7dea9-1545-4bcf-9402-5e7c3e2fadc1
    slug: circleci/W3itJ28HV7uhLEPaTyXX9H/AineBHFcxTseefh8cYviEt
    name: SSW-567
